### ISSUE TITLE
Use TailwindCSS 2.2 instead of Chakra UI

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#193]
## What feature would you like to have?

I'd really like for us to use a better framework for our website styling. If we're going to the effort to re-build our site anyways, we might want to consider moving to TailwindCSS 2.2?

https://tailwindcss.com/

I just wanted to discuss this with you, don't feel pressured into anything. 😉 

**Differences in philosophy:**

Chakra UI is basically "batteries included" components, with limited styling afterwards, altering components can be done, but might run into troubles with inheritance of other styles.

TailwindCSS is "utility first", where you built the component yourself, with full control over the looks. All styling is right next to the code. And this is the big one: whatever styling you see in the code, is the styling of the final component. TailwindCSS basically opt-out of the cascading part of CSS.

I really, really like TailwindCSS, the documentation for that project is complete, functional and looks really nice to boot.
I think TailwindCSS has great looking defaults (that's why I grabbed their colorscheme for our design).

**Benefits of moving to TailwindCSS:**

- Way better documentation
- When you look a the code, that's what you get, all state of the component is visible in the React/HTML code
- Has variants for different breakpoints
- Has easy way to make a hover,focus,active variant
- Has great default theme/styling/spacing/breakpoints
- Works with Next.js (The tailwind docs site uses it)

**Drawbacks of moving to TailwindCSS:**

- It's basically pressing the "reset" button on the whole app
- All components need to be built out by hand
- Logic that's currently baked into Chakra UI is gone, and needs to be replicated
- The code will contain more classes, and will look a bit messier
- It will be a lot, lot of work to redo the app

## What problem will be solved by having the feature?

Use a design system with sensible and nice looking defaults.
Have full control of the styling of our components.
One place to change styling for a component (no inheritance!).

I think making the move will actually lead to reduced maintenance headaches over time, with the drawback of a big major upfront cost of doing the migration.

## Do you want to help making the feature?

I know a bit of TailwindCSS, but not enough to do the migration.

**Comment by Belco90** [comment]
Hey @HonkingGoose!

Thanks for your proposal, but to be honest I'm not thinking about switching Chakra UI by anything else in short term.

I decided to use Chakra because it has great defaults, it's really easy to customize, but also because it provides an amazing bunch of components with a fantastic a11y out of the box. This is pretty important to me so I can focus on the logic of the app without needing to work that much to have a nice UI/UX.

Anyway, Chakra UI allows you to build complex interfaces and customize everything you want. I used Chakra in the company I used to work for to build a complex layout for displaying pieces of media from influencers in a fancy way. The design was really heavy for that app, there is nothing we couldn't do with Chakra.

I think you must be confused with how to set up Chakra's theme. Every time I point "we need to change X in Chakra's theme", that's not the only way you have to do it! That's only to establish the defaults of the design system, but Chakra is based on CSS-in-JS, built on top of [emotion](https://emotion.sh/docs/introduction). This means you can write css within any component in a styled-components way, so we can customize whatever we need (you can find tons of examples in emotion docs).

> **What problem will be solved by having the feature?**
> Use a design system with sensible and nice looking defaults.
> Have full control of the styling of our components.
> One place to change styling for a component (no inheritance!).

I don't think moving to Tailwind would solve any of these to be honest:
- Chakra is already a design system (I guess "nice looking defaults" depends on each one taste 😛 )
- We have full control of the styling of our components with Chakra
- We can use inheritance in Chakra (i.e. get styles from the theme) or change it in one place/component (through emotion)

> **Benefits of moving to TailwindCSS:**
> 
>     Way better documentation
I think both Tailwind and Chakra have a great documentation. Obviously Chakra one is more oriented to developers, but I find it really useful and well organized.

>     When you look a the code, that's what you get, all state of the component is visible in the React/HTML code
That's the same with Chakra UI (and all CSS-in-JS solutions in general). Obviously, Chakra has tons of [style props](https://chakra-ui.com/docs/features/style-props) you need to be aware of, but they are quite intuitive.

>     Has variants for different breakpoints
Chakra too! You can find [more info here](https://chakra-ui.com/docs/features/responsive-styles), but basically, the idea is: Chakra define some breakpoints (that can be overwritten or extended), and then most of the component props can be set using an array/object to indicate different values based on the viewport size. This is used in our codebase in several places, take a look at our Layout component for example: it has a Box with a dynamic margin-top depending on the viewport size/breakpoints.

>     Has easy way to make a hover,focus,active variant
You have [all pseudo props available in Chakra](https://chakra-ui.com/docs/features/style-props#pseudo) too.

>     Has great default theme/styling/spacing/breakpoints
Again, I think it's a matter of taste. Chakra's defaults are not the best one I've seen in my life, but is good enough to start with. And then it's really easy to customize/extend.

>     Works with Next.js (The tailwind docs site uses it)
Well, this project is using Next.js + Chakra (and [it's officially supported](https://chakra-ui.com/guides/with-nextjs)) so that's not a Tailwind advantage, right?

---

I guess this is all about a matter of design (utility classes) vs development (style props) approach, but in terms of customization don't worry about Chakra since it will allow us to do everything we need.

**Comment by HonkingGoose** [comment]
First of all, thank you for the in-depth response! I can see that you've really thought about this. So even though we won't be moving over, I appreciate you going over your thoughts on this! ❤️ 

---

> I decided to use Chakra because it has great defaults, it's really easy to customize, but also because it provides an amazing bunch of components with a fantastic a11y out of the box. This is pretty important to me so I can focus on the logic of the app without needing to work that much to have a nice UI/UX.

TailwindCSS does not come with nice components out of the box, their whole thing is that you build those yourself. So that's a big win for Chakra UI.

> Anyway, Chakra UI allows you to build complex interfaces and customize everything you want. I used Chakra in the company I used to work for to build a complex layout for displaying pieces of media from influencers in a fancy way. The design was really heavy for that app, there is nothing we couldn't do with Chakra.

I can see that you've battle tested Chakra UI for a major app, so I shouldn't be too worried that we cannot build the nice stuff I designed for us! 😄 

> I think you must be confused with how to set up Chakra's theme. Every time I point "we need to change X in Chakra's theme", that's not the only way you have to do it! That's only to establish the defaults of the design system, but Chakra is based on CSS-in-JS, built on top of [emotion](https://emotion.sh/docs/introduction). This means you can write css within any component in a styled-components way, so we can customize whatever we need (you can find tons of examples in emotion docs).

I think this is the root cause of me wanting to move over to TailwindCSS. With TailwindCSS, I know where to find everything in their docs, and know how to nudge the code to get things looking the way I want. With ChrakaUI, I'm basically going in blind. So that's scary for me!

I notice sometimes we use a `as` property to override something from the ChakraUI component, and sometimes we define custom colors, like in PR #186. So I worry that we're spreading our styles all over the place.

The desired end-state for me would be that we have a single source of truth for common things like: font-styles, buttons, shadows, colors, text colors, etc.

> I don't think moving to Tailwind would solve any of these to be honest:
> 
>     * Chakra is already a design system (I guess "nice looking defaults" depends on each one taste 😛 )
> 
>     * We have full control of the styling of our components with Chakra
> 
>     * We can use inheritance in Chakra (i.e. get styles from the theme) or change it in one place/component (through emotion)

If we're not fixing any major pain points on your side with the move, let's keep things as they are! 😉

I think I just need some re-assurance that we'll be able to build the nice things, and that we will end up with something that we both can customize/understand in the end. 😄

**Comment by Belco90** [comment]
> First of all, thank you for the in-depth response! I can see that you've really thought about this.

No problem! I've read a lot about Tailwind and played with it, even considered it for this webapp at some point but as you pointed, Chakra components made everything simpler to me. Anyway, [Chakra has a comparison against Tailwind](https://chakra-ui.com/docs/comparison#how-is-chakra-different-from-tailwind-css) in case you want to read more about their differences.

The main disadvantage from Chakra compared to Tailwind is that the former is based on CSS-in-JS which will run some JS code to "compute" the final css in the real website, while the latter output a completely static css, so it's pure in terms of styling. However, I haven't ran into any performance issues, not even in that complex webapp I built in my previous job, so I wouldn't worry about that (at least for now).

> I think this is the root cause of me wanting to move over to TailwindCSS. With TailwindCSS, I know where to find everything in their docs, and know how to nudge the code to get things looking the way I want. With ChrakaUI, I'm basically going in blind. So that's scary for me!
> 
> I notice sometimes we use a `as` property to override something from the ChakraUI component, and sometimes we define custom colors, like in PR #186. So I worry that we're spreading our styles all over the place.

Yeah, I agree you need more background in that sense to work with Chakra. For example, the `as` prop is an abstraction that allows separating styling from semantics. For example, we might be interested in rendering a heading with level 2 but with the design of heading 3.

With `as` prop we can set the styles through a Chakra component/props (`<Heading size="4xl">`) and then indicate how to render it semantically (`as="h3"`). This is an amazing separation, to be honest. As a frontend developer, I've wanted to split those 2 concerns so many times in the past that I love to be able to do so.

About defining custom colors or theme properties, I'd say Chakra has the same problem as Tailwind (and potentially any Design System)? So you define tokens in the theme but then you can't make 100% sure all your code is using them but hardcoded values instead. I'd say that's more explicit with Chakra since you should always use components and not write HTML tags directly, so it's easier to spot. Still, this can only be spotted on code review.

> The desired end-state for me would be that we have a single source of truth for common things like: font-styles, buttons, shadows, colors, text colors, etc.

Not sure if I follow you here. We have a single source of truth here, which is the Chakra theme. That theme (default one or extended one) is the source of truth used in all Chakra components (and even [Chakra factory](https://chakra-ui.com/docs/features/chakra-factory)). Then you can create your own components on top of Chakra reusing those tokens or use css which doesn't follow those tokens, but that could happen in the same way in Tailwind (I could use a custom class outside Tailwind utilities).

To wrap up the whole discussion (which I'm happy you brought to the table!), this doesn't mean I'll stick forever to Chakra, but it's covering all my necessities for this project, allowing me to implement all the design changes needed from your side (even if you can't do that yourself).

**Comment by HonkingGoose** [comment]
> With `as` prop we can set the styles through a Chakra component/props (`<Heading size="4xl">`) and then indicate how to render it semantically (`as="h3"`). This is an amazing separation, to be honest. As a frontend developer, I've wanted to split those 2 concerns so many times in the past that I love to be able to do so.

Ah okay, so it says: "Semantically this is a `h3` but we can style it with `<Heading size="4xl">`. You're right separating those concerns is a good thing!

---

> About defining custom colors or theme properties, I'd say Chakra has the same problem as Tailwind (and potentially any Design System)? So you define tokens in the theme but then you can't make 100% sure all your code is using them but hardcoded values instead. I'd say that's more explicit with Chakra since you should always use components and not write HTML tags directly, so it's easier to spot. Still, this can only be spotted on code review.

The idea with TailwindCSS is that you don't write any custom CSS, you use their classes to do things. The idea with TailwindCSS is that you create components for recurring things like badges, buttons, etc. And then you only use those components.

I guess using components only in Chakra UI is giving us the same kinds of guarantees, maybe even better, because it forces you to componentize right away. 😄 

---

> > The desired end-state for me would be that we have a single source of truth for common things like: font-styles, buttons, shadows, colors, text colors, etc.
> 
> Not sure if I follow you here. We have a single source of truth here, which is the Chakra theme. That theme (default one or extended one) is the source of truth used in all Chakra components (and even [Chakra factory](https://chakra-ui.com/docs/features/chakra-factory)). Then you can create your own components on top of Chakra reusing those tokens or use css which doesn't follow those tokens, but that could happen in the same way in Tailwind (I could use a custom class outside Tailwind utilities).

I really need to read up on that Chakra UI custom theme thing, because I don't understand a thing about this... 😄 

The main point I'm trying to make here is that we should be careful "how and where" we add our own custom overrides to the Chakra UI default style. So if we want a link to look a certain way, we should fix that in one location, so all links look the same, etc. 😄 

---

> To wrap up the whole discussion (which I'm happy you brought to the table!), this doesn't mean I'll stick forever to Chakra, but it's covering all my necessities for this project, allowing me to implement all the design changes needed from your side (even if you can't do that yourself).

Glad to discuss it with you! ❤️ 

Good to hear that Chakra UI is covering all the necessities, and that you'll be able to build the design with it. I hope that I can get good enough with Chakra UI together with you, so that I can maybe help "nudge" components into the correct scaling/size/font/colors. 😄 

Now I don't have to think "If only I mentioned TailwindCSS before we started our massive rebuild of the site". 😉 

I'll close this issue, as we've decided to stay with Chakra UI. 😉

**Comment by Belco90** [comment]
> The main point I'm trying to make here is that we should be careful "how and where" we add our own custom overrides to the Chakra UI default style. So if we want a link to look a certain way, we should fix that in one location, so all links look the same, etc. 😄

Ok, I got it now. So there are two things to change in Chakra related to that: theme and components.

Customizing the theme would be the same as customizing Tailwind util classes, so Chakra components can use theme tokens and will be translated into custom values through the theme. This is done through our `customTheme.ts` file using Chakra `extendTheme` util. We can modify current tokens or add new ones. An example for this would be modifying default colors or fonts.

Then we can also customize things at the components level. There is no component customized so far in this project, but it's definitely possible using [Chakra Component Style API](https://chakra-ui.com/docs/theming/component-style). This isn't as simple as customizing the theme of course, but it allows us to tweak tons of things for Chakra components. An example for this would be making all buttons to be rounded by default: I don't need to go button by button modifying this, or create my own Button component inheriting the base one from Chakra to then round it; it would be as simple as setting desired border-radius in `baseStyle` for `Button` component, and then pass it to `extendTheme` util again.

**Comment by HonkingGoose** [comment]
> Then we can also customize things at the components level. There is no component customized so far in this project (though I'll have to do it to apply your design for sure), but it's definitely possible using [Chakra Component Style API](https://chakra-ui.com/docs/theming/component-style). This isn't as simple as customizing the theme of course, but it allows us to tweak tons of things for Chakra components.

Yeah the code is a bit much for me to understand, but I understand the button design picture on that page! It shows two different buttons, and the code to create those buttons.

So whatever I build in Figma, we could componentize via that system if we need to. 😄 

> An example for this would be making all buttons to be rounded by default: I don't need to go button by button modifying this, or create my own Button component inheriting the base one from Chakra to then round it; it would be as simple as setting the desired border-radius in `baseStyle` for `Button` component, and then pass it to `extendTheme` util again.

The worry I had was that we would be going all over our code to set `border-radius: 15` on each and every button we use in our code... 🤪  But luckily we don't need to do that! 😄
