### ISSUE TITLE
Require E2E tests to pass before merging

### ISSUE THREAD

**Issue by HonkingGoose** [Belco90/octoclairvoyant#376]
### What feature would you like to have?

Right now the only required test is `Lint / lint (14.x) (pull_request)`.

I think we should also require the E2E Cypress tests to pass before merging?

To do this you can go to repository setting -> branch protection for the `main` branch, and change the require tests to pass before merging section.

### What problem will this feature solve?

Prevent accidental merges of PRs that don't pass the required tests.

### Do you want to help make the feature?

No

### Is there anything else we need to know?

I don't have rights to change our branch protection rules, so @Belco90 will have to do that for us. 😉

**Comment by Belco90** [comment]
Done, although I have to admit I'm not a big fan of the current implementation of this feature:

-  it's really brittle so when one of the job's names is changed (e.g. we migrate from node v14 to v16 the names will change from 14.x to 16.x), it will require an unexisting job to get passed, blocking the PR merges until we update this rule.
- it's not really flexible so it applies the same rules to every single PR. This is not affecting this repo, but I have others where I'm skipping the tests for some specific PRs (e.g. all-contributors PRs) so again it blocks those PRs from being merged since can't find required jobs passing.

**Comment by HonkingGoose** [comment]
If it turns out we don't like it, you can always revert this change. 😉
